//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderMediaPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderMediaPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Jump Backward (Large) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpBackwardLargeStep {
            get {
                return ResourceManager.GetString("JumpBackwardLargeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Backward (Medium) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpBackwardMediumStep {
            get {
                return ResourceManager.GetString("JumpBackwardMediumStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Backward (Small) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpBackwardSmallStep {
            get {
                return ResourceManager.GetString("JumpBackwardSmallStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Forward (Large) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpForwardLargeStep {
            get {
                return ResourceManager.GetString("JumpForwardLargeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Forward (Medium) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpForwardMediumStep {
            get {
                return ResourceManager.GetString("JumpForwardMediumStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Forward (Small) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpForwardSmallStep {
            get {
                return ResourceManager.GetString("JumpForwardSmallStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump to the beginning  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpToBegin {
            get {
                return ResourceManager.GetString("JumpToBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump to the Ending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JumpToEnd {
            get {
                return ResourceManager.GetString("JumpToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextMedia {
            get {
                return ResourceManager.GetString("NextMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviousMedia {
            get {
                return ResourceManager.GetString("PreviousMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeedDown {
            get {
                return ResourceManager.GetString("SpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeedUp {
            get {
                return ResourceManager.GetString("SpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switching Fullscreen Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleFullScreen {
            get {
                return ResourceManager.GetString("ToggleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause/Resume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TogglePauseAndResume {
            get {
                return ResourceManager.GetString("TogglePauseAndResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleStopAndPlay {
            get {
                return ResourceManager.GetString("ToggleStopAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
    }
}
