//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderMediaPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Memorized")]
        public string StartupWindowMode {
            get {
                return ((string)(this["StartupWindowMode"]));
            }
            set {
                this["StartupWindowMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nothing")]
        public string ResizeModeWhenPlayingVideo {
            get {
                return ((string)(this["ResizeModeWhenPlayingVideo"]));
            }
            set {
                this["ResizeModeWhenPlayingVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public string LastWindowWidth {
            get {
                return ((string)(this["LastWindowWidth"]));
            }
            set {
                this["LastWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public string LastWindowHeight {
            get {
                return ((string)(this["LastWindowHeight"]));
            }
            set {
                this["LastWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public string SpecifiedWindowWidth {
            get {
                return ((string)(this["SpecifiedWindowWidth"]));
            }
            set {
                this["SpecifiedWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public string SpecifiedWindowHeight {
            get {
                return ((string)(this["SpecifiedWindowHeight"]));
            }
            set {
                this["SpecifiedWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string AdjustVideoSizeScaling {
            get {
                return ((string)(this["AdjustVideoSizeScaling"]));
            }
            set {
                this["AdjustVideoSizeScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string FitToScreenSizeScaling {
            get {
                return ((string)(this["FitToScreenSizeScaling"]));
            }
            set {
                this["FitToScreenSizeScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string RestoreWindowPosition {
            get {
                return ((string)(this["RestoreWindowPosition"]));
            }
            set {
                this["RestoreWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string FixAspectRatio {
            get {
                return ((string)(this["FixAspectRatio"]));
            }
            set {
                this["FixAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public string LastWindowLeft {
            get {
                return ((string)(this["LastWindowLeft"]));
            }
            set {
                this["LastWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public string LastWindowTop {
            get {
                return ((string)(this["LastWindowTop"]));
            }
            set {
                this["LastWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string OnScreenPlaybackTimeDisplay {
            get {
                return ((string)(this["OnScreenPlaybackTimeDisplay"]));
            }
            set {
                this["OnScreenPlaybackTimeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string OnScreenVolumeDisplay {
            get {
                return ((string)(this["OnScreenVolumeDisplay"]));
            }
            set {
                this["OnScreenVolumeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NextMedia")]
        public string PlaybackEndBehavier {
            get {
                return ((string)(this["PlaybackEndBehavier"]));
            }
            set {
                this["PlaybackEndBehavier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PlaybackBehavierNLoopN {
            get {
                return ((string)(this["PlaybackBehavierNLoopN"]));
            }
            set {
                this["PlaybackBehavierNLoopN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string OnScreenTitleDisplay {
            get {
                return ((string)(this["OnScreenTitleDisplay"]));
            }
            set {
                this["OnScreenTitleDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume")]
        public string MouseWheelBehavier {
            get {
                return ((string)(this["MouseWheelBehavier"]));
            }
            set {
                this["MouseWheelBehavier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoChange")]
        public string PlaybackVolume {
            get {
                return ((string)(this["PlaybackVolume"]));
            }
            set {
                this["PlaybackVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public string LastVolume {
            get {
                return ((string)(this["LastVolume"]));
            }
            set {
                this["LastVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public string SpecifiedVolume {
            get {
                return ((string)(this["SpecifiedVolume"]));
            }
            set {
                this["SpecifiedVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string OnScreenSpeedDisplay {
            get {
                return ((string)(this["OnScreenSpeedDisplay"]));
            }
            set {
                this["OnScreenSpeedDisplay"] = value;
            }
        }
    }
}
